CC=gcc
CFLAGS=-g -Wall -std=gnu99

all: mysmtpd mypopd

mysmtpd: mysmtpd.o netbuffer.o mailuser.o server.o
mypopd: mypopd.o netbuffer.o mailuser.o server.o

mysmtpd.o: mysmtpd.c netbuffer.h mailuser.h server.h
mypopd.o: mypopd.c netbuffer.h mailuser.h server.h

netbuffer.o: netbuffer.c netbuffer.h
mailuser.o: mailuser.c mailuser.h
server.o: server.c server.h

clean:
	-rm -rf mysmtpd mypopd mysmtpd.o mypopd.o netbuffer.o mailuser.o server.o
cleanall: clean
	-rm -rf *~

build: sync
	@echo "Building Assignment on CS server"
	@ssh -t q7h0b@remote.ugrad.cs.ubc.ca "\
		cd ~/cs317/a3 && \
		make all "

sync:
	@echo "Syncing files to remote CS server"
	@rsync \
		--recursive --links --perms --partial --progress --force \
		--delete --delete-excluded \
		./ q7h0b@remote.ugrad.cs.ubc.ca:~/cs317/a3